name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Set RELEASE_TAG env
        run: |
          echo RELEASE_TAG=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
          echo "Move ./changelog/v0.0.0-NEXT.md to ./changelog/${RELEASE_TAG}.md"
          sed -i "s/^## v0.0.0-NEXT$/## ${RELEASE_TAG}/" ./changelog/v0.0.0-NEXT.md
          mv ./changelog/v0.0.0-NEXT.md ./changelog/${RELEASE_TAG}.md
      -
          name: CAT NEXT File
          run: |
            cat changelog/v0.0.0-NEXT.md         
      -
          name: CAT TAG File
          run: |
            cat changelog/${RELEASE_TAG}.md
      -
        name: Commit ChangeLog
        uses: EndBug/add-and-commit@v7
        with:
          add: "['changelog/v0.0.0-NEXT.md', 'changelog/${RELEASE_TAG}.md']"
          committer_name: Christopher Maahs
          committer_email: cmaahs@gmail.com
          message: "Update Release ${RELEASE_TAG}.md changelog"
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --release-notes=changelog/${{ env.RELEASE_TAG }}.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAAHSOME_PAT: ${{ secrets.MAAHSOME_PAT }}
